name: Create a release in Octopus
on:
  push:
    branches:
      - aneita-test-octopus

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create a release in Octopus
    permissions:
      # Add any additional permissions your job requires here
      id-token: write # This is required to obtain the ID token from GitHub Actions
      contents: read # For example: this is required to check out code, remove if not needed
    steps:
      - name: Login to Octopus Deploy 
        uses: OctopusDeploy/login@v1
        with: 
          server: https://octoneita.octopus.app
          service_account_id: 769045ce-7846-454f-8597-28d8d9773ac2

      - name: Create Octopus release
        uses: OctopusDeploy/create-release-action@v3
        with:
          space: Default
          project: 01. Basic Script App